### ISSUE TITLE
Request for Supporting Azure as a Public Cloud TEE

### ISSUE THREAD

**Issue by bhatiaanant** [WICG/protected-auction-services-discussion#67] opened 2024-04-29 18:53 UTC
Cloud Service Provider: Microsoft Azure

Web Address: https://azure.microsoft.com/en-us

Short Description:

Microsoft Azure is a leading cloud computing platform that offers a comprehensive set of services for building, deploying, and managing applications across a global network of data centers. Azure provides a secure and reliable environment with a focus on data privacy, encryption, and access control.

Security Properties: Azure offers a multi-layered security approach that includes physical, infrastructure, and operational security measures. Azure services are built on a foundation of trust with robust security features like encryption at rest and in transit, key management services, and identity and access management.

Remote Attestation: Azure supports remote attestation, a process that allows users to verify the integrity of a running virtual machine (VM). This helps ensure that the VM hasn't been tampered with and is running the expected code.

Workload Capabilities: Azure offers a wide range of workload capabilities to support various needs.  It can handle virtual machines, containers, serverless functions, and a vast array of data management and analytics services.

Security and Trust:

Microsoft Azure is committed to providing a secure and trustworthy cloud platform. Here's a breakdown of its security posture:

Compliance: Azure adheres to a wide range of industry standards and regulations, including ISO 27001, ISO 27018, and SOC compliance certifications. You can find a detailed list of Azure's compliance offerings here: https://www.microsoft.com/en-us/trust-center/compliance/compliance-overview

Cloud Security Certifications: Azure has achieved various cloud security industry certifications, including certifications for specific regions and services. Details on these certifications can be found here: https://www.microsoft.com/en-us/trust-center/compliance/compliance-overview

Inclusion in Research Reports:  Gartner and other leading research firms consistently recognize Microsoft Azure as a leader in the cloud computing market. You can find relevant Gartner reports here: https://cloud.google.com/resources/gartner-cloud-infrastructure-and-platform-services-2022

Microsoft Azure provides extensive documentation on its security features, compliance certifications, and workload capabilities. You can explore these resources on the Microsoft Azure website.

**Comment by palenica** [comment] 2024-05-15 14:24
Marking as duplicate of #31

**Closed** 2024-05-16 17:38 UTC
